/**
 * generated by Xtext 2.37.0
 */
package org.xtext.geodes.trustdsl.trustDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Agent</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.geodes.trustdsl.trustDSL.TrustDSLPackage#getAgent()
 * @model
 * @generated
 */
public interface Agent extends Element
{
} // Agent
