/**
 * generated by Xtext 2.37.0
 */
package org.xtext.geodes.trustdsl.trustDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SBoolean</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.geodes.trustdsl.trustDSL.SBoolean#getBelief <em>Belief</em>}</li>
 *   <li>{@link org.xtext.geodes.trustdsl.trustDSL.SBoolean#getDisbelief <em>Disbelief</em>}</li>
 *   <li>{@link org.xtext.geodes.trustdsl.trustDSL.SBoolean#getUncertainty <em>Uncertainty</em>}</li>
 *   <li>{@link org.xtext.geodes.trustdsl.trustDSL.SBoolean#getBaseRate <em>Base Rate</em>}</li>
 * </ul>
 *
 * @see org.xtext.geodes.trustdsl.trustDSL.TrustDSLPackage#getSBoolean()
 * @model
 * @generated
 */
public interface SBoolean extends EObject
{
  /**
   * Returns the value of the '<em><b>Belief</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Belief</em>' attribute.
   * @see #setBelief(double)
   * @see org.xtext.geodes.trustdsl.trustDSL.TrustDSLPackage#getSBoolean_Belief()
   * @model
   * @generated
   */
  double getBelief();

  /**
   * Sets the value of the '{@link org.xtext.geodes.trustdsl.trustDSL.SBoolean#getBelief <em>Belief</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Belief</em>' attribute.
   * @see #getBelief()
   * @generated
   */
  void setBelief(double value);

  /**
   * Returns the value of the '<em><b>Disbelief</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Disbelief</em>' attribute.
   * @see #setDisbelief(double)
   * @see org.xtext.geodes.trustdsl.trustDSL.TrustDSLPackage#getSBoolean_Disbelief()
   * @model
   * @generated
   */
  double getDisbelief();

  /**
   * Sets the value of the '{@link org.xtext.geodes.trustdsl.trustDSL.SBoolean#getDisbelief <em>Disbelief</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Disbelief</em>' attribute.
   * @see #getDisbelief()
   * @generated
   */
  void setDisbelief(double value);

  /**
   * Returns the value of the '<em><b>Uncertainty</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Uncertainty</em>' attribute.
   * @see #setUncertainty(double)
   * @see org.xtext.geodes.trustdsl.trustDSL.TrustDSLPackage#getSBoolean_Uncertainty()
   * @model
   * @generated
   */
  double getUncertainty();

  /**
   * Sets the value of the '{@link org.xtext.geodes.trustdsl.trustDSL.SBoolean#getUncertainty <em>Uncertainty</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Uncertainty</em>' attribute.
   * @see #getUncertainty()
   * @generated
   */
  void setUncertainty(double value);

  /**
   * Returns the value of the '<em><b>Base Rate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Base Rate</em>' attribute.
   * @see #setBaseRate(double)
   * @see org.xtext.geodes.trustdsl.trustDSL.TrustDSLPackage#getSBoolean_BaseRate()
   * @model
   * @generated
   */
  double getBaseRate();

  /**
   * Sets the value of the '{@link org.xtext.geodes.trustdsl.trustDSL.SBoolean#getBaseRate <em>Base Rate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Base Rate</em>' attribute.
   * @see #getBaseRate()
   * @generated
   */
  void setBaseRate(double value);

} // SBoolean
