/**
 * generated by Xtext 2.37.0
 */
package org.xtext.geodes.trustdsl.trustDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Trust Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.geodes.trustdsl.trustDSL.TrustModel#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see org.xtext.geodes.trustdsl.trustDSL.TrustDSLPackage#getTrustModel()
 * @model
 * @generated
 */
public interface TrustModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.geodes.trustdsl.trustDSL.Element}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see org.xtext.geodes.trustdsl.trustDSL.TrustDSLPackage#getTrustModel_Elements()
   * @model containment="true"
   * @generated
   */
  EList<Element> getElements();

} // TrustModel
