/**
 * generated by Xtext 2.37.0
 */
package org.xtext.geodes.trustdsl.trustDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Uncertain Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.geodes.trustdsl.trustDSL.UncertainElement#getBeliefs <em>Beliefs</em>}</li>
 * </ul>
 *
 * @see org.xtext.geodes.trustdsl.trustDSL.TrustDSLPackage#getUncertainElement()
 * @model
 * @generated
 */
public interface UncertainElement extends Element
{
  /**
   * Returns the value of the '<em><b>Beliefs</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.geodes.trustdsl.trustDSL.Belief}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Beliefs</em>' containment reference list.
   * @see org.xtext.geodes.trustdsl.trustDSL.TrustDSLPackage#getUncertainElement_Beliefs()
   * @model containment="true"
   * @generated
   */
  EList<Belief> getBeliefs();

} // UncertainElement
