/**
 * generated by Xtext 2.37.0
 */
package org.xtext.geodes.trustdsl.trustDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Uncertain Element Fusion</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.geodes.trustdsl.trustDSL.UncertainElementFusion#getBeliefs <em>Beliefs</em>}</li>
 *   <li>{@link org.xtext.geodes.trustdsl.trustDSL.UncertainElementFusion#getAleatoryCumulativeBF <em>Aleatory Cumulative BF</em>}</li>
 *   <li>{@link org.xtext.geodes.trustdsl.trustDSL.UncertainElementFusion#getAverageingBF <em>Averageing BF</em>}</li>
 *   <li>{@link org.xtext.geodes.trustdsl.trustDSL.UncertainElementFusion#getBeliefConstraintFusion <em>Belief Constraint Fusion</em>}</li>
 *   <li>{@link org.xtext.geodes.trustdsl.trustDSL.UncertainElementFusion#getConsensusCompromiseBF <em>Consensus Compromise BF</em>}</li>
 *   <li>{@link org.xtext.geodes.trustdsl.trustDSL.UncertainElementFusion#getEpistemicCumulativeBF <em>Epistemic Cumulative BF</em>}</li>
 *   <li>{@link org.xtext.geodes.trustdsl.trustDSL.UncertainElementFusion#getWeightedBF <em>Weighted BF</em>}</li>
 * </ul>
 *
 * @see org.xtext.geodes.trustdsl.trustDSL.TrustDSLPackage#getUncertainElementFusion()
 * @model
 * @generated
 */
public interface UncertainElementFusion extends Element
{
  /**
   * Returns the value of the '<em><b>Beliefs</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.geodes.trustdsl.trustDSL.Belief}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Beliefs</em>' containment reference list.
   * @see org.xtext.geodes.trustdsl.trustDSL.TrustDSLPackage#getUncertainElementFusion_Beliefs()
   * @model containment="true"
   * @generated
   */
  EList<Belief> getBeliefs();

  /**
   * Returns the value of the '<em><b>Aleatory Cumulative BF</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Aleatory Cumulative BF</em>' containment reference.
   * @see #setAleatoryCumulativeBF(SBoolean)
   * @see org.xtext.geodes.trustdsl.trustDSL.TrustDSLPackage#getUncertainElementFusion_AleatoryCumulativeBF()
   * @model containment="true"
   * @generated
   */
  SBoolean getAleatoryCumulativeBF();

  /**
   * Sets the value of the '{@link org.xtext.geodes.trustdsl.trustDSL.UncertainElementFusion#getAleatoryCumulativeBF <em>Aleatory Cumulative BF</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Aleatory Cumulative BF</em>' containment reference.
   * @see #getAleatoryCumulativeBF()
   * @generated
   */
  void setAleatoryCumulativeBF(SBoolean value);

  /**
   * Returns the value of the '<em><b>Averageing BF</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Averageing BF</em>' containment reference.
   * @see #setAverageingBF(SBoolean)
   * @see org.xtext.geodes.trustdsl.trustDSL.TrustDSLPackage#getUncertainElementFusion_AverageingBF()
   * @model containment="true"
   * @generated
   */
  SBoolean getAverageingBF();

  /**
   * Sets the value of the '{@link org.xtext.geodes.trustdsl.trustDSL.UncertainElementFusion#getAverageingBF <em>Averageing BF</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Averageing BF</em>' containment reference.
   * @see #getAverageingBF()
   * @generated
   */
  void setAverageingBF(SBoolean value);

  /**
   * Returns the value of the '<em><b>Belief Constraint Fusion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Belief Constraint Fusion</em>' containment reference.
   * @see #setBeliefConstraintFusion(SBoolean)
   * @see org.xtext.geodes.trustdsl.trustDSL.TrustDSLPackage#getUncertainElementFusion_BeliefConstraintFusion()
   * @model containment="true"
   * @generated
   */
  SBoolean getBeliefConstraintFusion();

  /**
   * Sets the value of the '{@link org.xtext.geodes.trustdsl.trustDSL.UncertainElementFusion#getBeliefConstraintFusion <em>Belief Constraint Fusion</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Belief Constraint Fusion</em>' containment reference.
   * @see #getBeliefConstraintFusion()
   * @generated
   */
  void setBeliefConstraintFusion(SBoolean value);

  /**
   * Returns the value of the '<em><b>Consensus Compromise BF</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Consensus Compromise BF</em>' containment reference.
   * @see #setConsensusCompromiseBF(SBoolean)
   * @see org.xtext.geodes.trustdsl.trustDSL.TrustDSLPackage#getUncertainElementFusion_ConsensusCompromiseBF()
   * @model containment="true"
   * @generated
   */
  SBoolean getConsensusCompromiseBF();

  /**
   * Sets the value of the '{@link org.xtext.geodes.trustdsl.trustDSL.UncertainElementFusion#getConsensusCompromiseBF <em>Consensus Compromise BF</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Consensus Compromise BF</em>' containment reference.
   * @see #getConsensusCompromiseBF()
   * @generated
   */
  void setConsensusCompromiseBF(SBoolean value);

  /**
   * Returns the value of the '<em><b>Epistemic Cumulative BF</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Epistemic Cumulative BF</em>' containment reference.
   * @see #setEpistemicCumulativeBF(SBoolean)
   * @see org.xtext.geodes.trustdsl.trustDSL.TrustDSLPackage#getUncertainElementFusion_EpistemicCumulativeBF()
   * @model containment="true"
   * @generated
   */
  SBoolean getEpistemicCumulativeBF();

  /**
   * Sets the value of the '{@link org.xtext.geodes.trustdsl.trustDSL.UncertainElementFusion#getEpistemicCumulativeBF <em>Epistemic Cumulative BF</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Epistemic Cumulative BF</em>' containment reference.
   * @see #getEpistemicCumulativeBF()
   * @generated
   */
  void setEpistemicCumulativeBF(SBoolean value);

  /**
   * Returns the value of the '<em><b>Weighted BF</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Weighted BF</em>' containment reference.
   * @see #setWeightedBF(SBoolean)
   * @see org.xtext.geodes.trustdsl.trustDSL.TrustDSLPackage#getUncertainElementFusion_WeightedBF()
   * @model containment="true"
   * @generated
   */
  SBoolean getWeightedBF();

  /**
   * Sets the value of the '{@link org.xtext.geodes.trustdsl.trustDSL.UncertainElementFusion#getWeightedBF <em>Weighted BF</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Weighted BF</em>' containment reference.
   * @see #getWeightedBF()
   * @generated
   */
  void setWeightedBF(SBoolean value);

} // UncertainElementFusion
