/*
 * generated by Xtext 2.37.0
 */
package org.w3.ns.prov.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.w3.ns.prov.ide.contentassist.antlr.internal.InternalProvNParser;
import org.w3.ns.prov.services.ProvNGrammarAccess;

public class ProvNParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(ProvNGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, ProvNGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getStatementAccess().getAlternatives(), "rule__Statement__Alternatives");
			builder.put(grammarAccess.getRelationAccess().getAlternatives(), "rule__Relation__Alternatives");
			builder.put(grammarAccess.getDateTimeAccess().getAlternatives(), "rule__DateTime__Alternatives");
			builder.put(grammarAccess.getDocumentAccess().getGroup(), "rule__Document__Group__0");
			builder.put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
			builder.put(grammarAccess.getNamespaceAccess().getGroup(), "rule__Namespace__Group__0");
			builder.put(grammarAccess.getEntityAccess().getGroup(), "rule__Entity__Group__0");
			builder.put(grammarAccess.getEntityAccess().getGroup_4(), "rule__Entity__Group_4__0");
			builder.put(grammarAccess.getEntityAccess().getGroup_4_3(), "rule__Entity__Group_4_3__0");
			builder.put(grammarAccess.getActivityAccess().getGroup(), "rule__Activity__Group__0");
			builder.put(grammarAccess.getActivityAccess().getGroup_4(), "rule__Activity__Group_4__0");
			builder.put(grammarAccess.getActivityAccess().getGroup_5(), "rule__Activity__Group_5__0");
			builder.put(grammarAccess.getActivityAccess().getGroup_6(), "rule__Activity__Group_6__0");
			builder.put(grammarAccess.getActivityAccess().getGroup_6_3(), "rule__Activity__Group_6_3__0");
			builder.put(grammarAccess.getAgentAccess().getGroup(), "rule__Agent__Group__0");
			builder.put(grammarAccess.getAgentAccess().getGroup_4(), "rule__Agent__Group_4__0");
			builder.put(grammarAccess.getAgentAccess().getGroup_4_3(), "rule__Agent__Group_4_3__0");
			builder.put(grammarAccess.getWasDerivedFromAccess().getGroup(), "rule__WasDerivedFrom__Group__0");
			builder.put(grammarAccess.getWasDerivedFromAccess().getGroup_5(), "rule__WasDerivedFrom__Group_5__0");
			builder.put(grammarAccess.getWasDerivedFromAccess().getGroup_6(), "rule__WasDerivedFrom__Group_6__0");
			builder.put(grammarAccess.getWasDerivedFromAccess().getGroup_6_3(), "rule__WasDerivedFrom__Group_6_3__0");
			builder.put(grammarAccess.getWasGeneratedByAccess().getGroup(), "rule__WasGeneratedBy__Group__0");
			builder.put(grammarAccess.getWasGeneratedByAccess().getGroup_5(), "rule__WasGeneratedBy__Group_5__0");
			builder.put(grammarAccess.getWasGeneratedByAccess().getGroup_6(), "rule__WasGeneratedBy__Group_6__0");
			builder.put(grammarAccess.getWasGeneratedByAccess().getGroup_6_3(), "rule__WasGeneratedBy__Group_6_3__0");
			builder.put(grammarAccess.getUsedAccess().getGroup(), "rule__Used__Group__0");
			builder.put(grammarAccess.getUsedAccess().getGroup_5(), "rule__Used__Group_5__0");
			builder.put(grammarAccess.getUsedAccess().getGroup_6(), "rule__Used__Group_6__0");
			builder.put(grammarAccess.getUsedAccess().getGroup_6_3(), "rule__Used__Group_6_3__0");
			builder.put(grammarAccess.getWasAssociatedWithAccess().getGroup(), "rule__WasAssociatedWith__Group__0");
			builder.put(grammarAccess.getWasAssociatedWithAccess().getGroup_5(), "rule__WasAssociatedWith__Group_5__0");
			builder.put(grammarAccess.getWasAssociatedWithAccess().getGroup_6(), "rule__WasAssociatedWith__Group_6__0");
			builder.put(grammarAccess.getWasAssociatedWithAccess().getGroup_6_3(), "rule__WasAssociatedWith__Group_6_3__0");
			builder.put(grammarAccess.getWasAttributedToAccess().getGroup(), "rule__WasAttributedTo__Group__0");
			builder.put(grammarAccess.getWasAttributedToAccess().getGroup_5(), "rule__WasAttributedTo__Group_5__0");
			builder.put(grammarAccess.getWasAttributedToAccess().getGroup_5_3(), "rule__WasAttributedTo__Group_5_3__0");
			builder.put(grammarAccess.getHadMemberAccess().getGroup(), "rule__HadMember__Group__0");
			builder.put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup_0(), "rule__QualifiedName__Group_0__0");
			builder.put(grammarAccess.getDateTimeAccess().getGroup_0(), "rule__DateTime__Group_0__0");
			builder.put(grammarAccess.getDocumentAccess().getCompartmentalModelAssignment_1(), "rule__Document__CompartmentalModelAssignment_1");
			builder.put(grammarAccess.getModelAccess().getNamespacesAssignment_1(), "rule__Model__NamespacesAssignment_1");
			builder.put(grammarAccess.getModelAccess().getStatementsAssignment_2(), "rule__Model__StatementsAssignment_2");
			builder.put(grammarAccess.getNamespaceAccess().getNameAssignment_2(), "rule__Namespace__NameAssignment_2");
			builder.put(grammarAccess.getNamespaceAccess().getUriAssignment_3(), "rule__Namespace__UriAssignment_3");
			builder.put(grammarAccess.getEntityAccess().getNameAssignment_3(), "rule__Entity__NameAssignment_3");
			builder.put(grammarAccess.getEntityAccess().getAttributesAssignment_4_2(), "rule__Entity__AttributesAssignment_4_2");
			builder.put(grammarAccess.getEntityAccess().getAttributesAssignment_4_3_1(), "rule__Entity__AttributesAssignment_4_3_1");
			builder.put(grammarAccess.getActivityAccess().getNameAssignment_3(), "rule__Activity__NameAssignment_3");
			builder.put(grammarAccess.getActivityAccess().getStartTimeAssignment_4_1(), "rule__Activity__StartTimeAssignment_4_1");
			builder.put(grammarAccess.getActivityAccess().getEndTimeAssignment_5_1(), "rule__Activity__EndTimeAssignment_5_1");
			builder.put(grammarAccess.getActivityAccess().getAttributesAssignment_6_2(), "rule__Activity__AttributesAssignment_6_2");
			builder.put(grammarAccess.getActivityAccess().getAttributesAssignment_6_3_1(), "rule__Activity__AttributesAssignment_6_3_1");
			builder.put(grammarAccess.getAgentAccess().getNameAssignment_3(), "rule__Agent__NameAssignment_3");
			builder.put(grammarAccess.getAgentAccess().getAttributesAssignment_4_2(), "rule__Agent__AttributesAssignment_4_2");
			builder.put(grammarAccess.getAgentAccess().getAttributesAssignment_4_3_1(), "rule__Agent__AttributesAssignment_4_3_1");
			builder.put(grammarAccess.getWasDerivedFromAccess().getGeneratedEntityAssignment_2(), "rule__WasDerivedFrom__GeneratedEntityAssignment_2");
			builder.put(grammarAccess.getWasDerivedFromAccess().getUsedEntityAssignment_4(), "rule__WasDerivedFrom__UsedEntityAssignment_4");
			builder.put(grammarAccess.getWasDerivedFromAccess().getTimeAssignment_5_1(), "rule__WasDerivedFrom__TimeAssignment_5_1");
			builder.put(grammarAccess.getWasDerivedFromAccess().getAttributesAssignment_6_2(), "rule__WasDerivedFrom__AttributesAssignment_6_2");
			builder.put(grammarAccess.getWasDerivedFromAccess().getAttributesAssignment_6_3_1(), "rule__WasDerivedFrom__AttributesAssignment_6_3_1");
			builder.put(grammarAccess.getWasGeneratedByAccess().getEntityAssignment_2(), "rule__WasGeneratedBy__EntityAssignment_2");
			builder.put(grammarAccess.getWasGeneratedByAccess().getActivityAssignment_4(), "rule__WasGeneratedBy__ActivityAssignment_4");
			builder.put(grammarAccess.getWasGeneratedByAccess().getTimeAssignment_5_1(), "rule__WasGeneratedBy__TimeAssignment_5_1");
			builder.put(grammarAccess.getWasGeneratedByAccess().getAttributesAssignment_6_2(), "rule__WasGeneratedBy__AttributesAssignment_6_2");
			builder.put(grammarAccess.getWasGeneratedByAccess().getAttributesAssignment_6_3_1(), "rule__WasGeneratedBy__AttributesAssignment_6_3_1");
			builder.put(grammarAccess.getUsedAccess().getActivityAssignment_2(), "rule__Used__ActivityAssignment_2");
			builder.put(grammarAccess.getUsedAccess().getEntityAssignment_4(), "rule__Used__EntityAssignment_4");
			builder.put(grammarAccess.getUsedAccess().getTimeAssignment_5_1(), "rule__Used__TimeAssignment_5_1");
			builder.put(grammarAccess.getUsedAccess().getAttributesAssignment_6_2(), "rule__Used__AttributesAssignment_6_2");
			builder.put(grammarAccess.getUsedAccess().getAttributesAssignment_6_3_1(), "rule__Used__AttributesAssignment_6_3_1");
			builder.put(grammarAccess.getWasAssociatedWithAccess().getActivityAssignment_2(), "rule__WasAssociatedWith__ActivityAssignment_2");
			builder.put(grammarAccess.getWasAssociatedWithAccess().getAgentAssignment_4(), "rule__WasAssociatedWith__AgentAssignment_4");
			builder.put(grammarAccess.getWasAssociatedWithAccess().getPlanAssignment_5_1(), "rule__WasAssociatedWith__PlanAssignment_5_1");
			builder.put(grammarAccess.getWasAssociatedWithAccess().getAttributesAssignment_6_2(), "rule__WasAssociatedWith__AttributesAssignment_6_2");
			builder.put(grammarAccess.getWasAssociatedWithAccess().getAttributesAssignment_6_3_1(), "rule__WasAssociatedWith__AttributesAssignment_6_3_1");
			builder.put(grammarAccess.getWasAttributedToAccess().getEntityAssignment_2(), "rule__WasAttributedTo__EntityAssignment_2");
			builder.put(grammarAccess.getWasAttributedToAccess().getAgentAssignment_4(), "rule__WasAttributedTo__AgentAssignment_4");
			builder.put(grammarAccess.getWasAttributedToAccess().getAttributesAssignment_5_2(), "rule__WasAttributedTo__AttributesAssignment_5_2");
			builder.put(grammarAccess.getWasAttributedToAccess().getAttributesAssignment_5_3_1(), "rule__WasAttributedTo__AttributesAssignment_5_3_1");
			builder.put(grammarAccess.getHadMemberAccess().getCollectionAssignment_2(), "rule__HadMember__CollectionAssignment_2");
			builder.put(grammarAccess.getHadMemberAccess().getMemberAssignment_4(), "rule__HadMember__MemberAssignment_4");
			builder.put(grammarAccess.getAttributeAccess().getLabelAssignment_0(), "rule__Attribute__LabelAssignment_0");
			builder.put(grammarAccess.getAttributeAccess().getValueAssignment_2(), "rule__Attribute__ValueAssignment_2");
			builder.put(grammarAccess.getDateTimeAccess().getYearAssignment_0_0(), "rule__DateTime__YearAssignment_0_0");
			builder.put(grammarAccess.getDateTimeAccess().getMonthAssignment_0_2(), "rule__DateTime__MonthAssignment_0_2");
			builder.put(grammarAccess.getDateTimeAccess().getDayAssignment_0_4(), "rule__DateTime__DayAssignment_0_4");
			builder.put(grammarAccess.getDateTimeAccess().getHourAssignment_0_6(), "rule__DateTime__HourAssignment_0_6");
			builder.put(grammarAccess.getDateTimeAccess().getMinuteAssignment_0_8(), "rule__DateTime__MinuteAssignment_0_8");
			builder.put(grammarAccess.getDateTimeAccess().getSecondAssignment_0_10(), "rule__DateTime__SecondAssignment_0_10");
			builder.put(grammarAccess.getDateTimeAccess().getDashAssignment_1(), "rule__DateTime__DashAssignment_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private ProvNGrammarAccess grammarAccess;

	@Override
	protected InternalProvNParser createParser() {
		InternalProvNParser result = new InternalProvNParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public ProvNGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ProvNGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
