/**
 * generated by Xtext 2.37.0
 */
package org.idm.cms.emodl.emodl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Import</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.idm.cms.emodl.emodl.Import#getGroups <em>Groups</em>}</li>
 * </ul>
 *
 * @see org.idm.cms.emodl.emodl.EmodlPackage#getImport()
 * @model
 * @generated
 */
public interface Import extends EObject
{
  /**
   * Returns the value of the '<em><b>Groups</b></em>' containment reference list.
   * The list contents are of type {@link org.idm.cms.emodl.emodl.ImportGroup}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Groups</em>' containment reference list.
   * @see org.idm.cms.emodl.emodl.EmodlPackage#getImport_Groups()
   * @model containment="true"
   * @generated
   */
  EList<ImportGroup> getGroups();

} // Import
