/**
 * generated by Xtext 2.37.0
 */
package org.idm.cms.emodl.emodl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Locale</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.idm.cms.emodl.emodl.EmodlPackage#getLocale()
 * @model
 * @generated
 */
public interface Locale extends Element
{
} // Locale
