/**
 * generated by Xtext 2.37.0
 */
package org.idm.cms.emodl.emodl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Reaction</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.idm.cms.emodl.emodl.Reaction#getInputSpecies <em>Input Species</em>}</li>
 *   <li>{@link org.idm.cms.emodl.emodl.Reaction#getOutputSpecies <em>Output Species</em>}</li>
 *   <li>{@link org.idm.cms.emodl.emodl.Reaction#getPropensityFunction <em>Propensity Function</em>}</li>
 * </ul>
 *
 * @see org.idm.cms.emodl.emodl.EmodlPackage#getReaction()
 * @model
 * @generated
 */
public interface Reaction extends Element
{
  /**
   * Returns the value of the '<em><b>Input Species</b></em>' reference list.
   * The list contents are of type {@link org.idm.cms.emodl.emodl.Species}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Input Species</em>' reference list.
   * @see org.idm.cms.emodl.emodl.EmodlPackage#getReaction_InputSpecies()
   * @model
   * @generated
   */
  EList<Species> getInputSpecies();

  /**
   * Returns the value of the '<em><b>Output Species</b></em>' reference list.
   * The list contents are of type {@link org.idm.cms.emodl.emodl.Species}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Output Species</em>' reference list.
   * @see org.idm.cms.emodl.emodl.EmodlPackage#getReaction_OutputSpecies()
   * @model
   * @generated
   */
  EList<Species> getOutputSpecies();

  /**
   * Returns the value of the '<em><b>Propensity Function</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Propensity Function</em>' containment reference.
   * @see #setPropensityFunction(Expression)
   * @see org.idm.cms.emodl.emodl.EmodlPackage#getReaction_PropensityFunction()
   * @model containment="true"
   * @generated
   */
  Expression getPropensityFunction();

  /**
   * Sets the value of the '{@link org.idm.cms.emodl.emodl.Reaction#getPropensityFunction <em>Propensity Function</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Propensity Function</em>' containment reference.
   * @see #getPropensityFunction()
   * @generated
   */
  void setPropensityFunction(Expression value);

} // Reaction
