/**
 * generated by Xtext 2.37.0
 */
package org.idm.cms.emodl.emodl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Species</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.idm.cms.emodl.emodl.Species#getInitialPopulation <em>Initial Population</em>}</li>
 * </ul>
 *
 * @see org.idm.cms.emodl.emodl.EmodlPackage#getSpecies()
 * @model
 * @generated
 */
public interface Species extends Element
{
  /**
   * Returns the value of the '<em><b>Initial Population</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Initial Population</em>' attribute.
   * @see #setInitialPopulation(double)
   * @see org.idm.cms.emodl.emodl.EmodlPackage#getSpecies_InitialPopulation()
   * @model
   * @generated
   */
  double getInitialPopulation();

  /**
   * Sets the value of the '{@link org.idm.cms.emodl.emodl.Species#getInitialPopulation <em>Initial Population</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Initial Population</em>' attribute.
   * @see #getInitialPopulation()
   * @generated
   */
  void setInitialPopulation(double value);

} // Species
