/**
 * generated by Xtext 2.37.0
 */
package org.idm.cms.emodl.emodl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>State Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.idm.cms.emodl.emodl.StateEvent#getPredicate <em>Predicate</em>}</li>
 *   <li>{@link org.idm.cms.emodl.emodl.StateEvent#getVariableValuePairs <em>Variable Value Pairs</em>}</li>
 * </ul>
 *
 * @see org.idm.cms.emodl.emodl.EmodlPackage#getStateEvent()
 * @model
 * @generated
 */
public interface StateEvent extends Element
{
  /**
   * Returns the value of the '<em><b>Predicate</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Predicate</em>' containment reference.
   * @see #setPredicate(Expression)
   * @see org.idm.cms.emodl.emodl.EmodlPackage#getStateEvent_Predicate()
   * @model containment="true"
   * @generated
   */
  Expression getPredicate();

  /**
   * Sets the value of the '{@link org.idm.cms.emodl.emodl.StateEvent#getPredicate <em>Predicate</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Predicate</em>' containment reference.
   * @see #getPredicate()
   * @generated
   */
  void setPredicate(Expression value);

  /**
   * Returns the value of the '<em><b>Variable Value Pairs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable Value Pairs</em>' containment reference.
   * @see #setVariableValuePairs(VariableValuePairs)
   * @see org.idm.cms.emodl.emodl.EmodlPackage#getStateEvent_VariableValuePairs()
   * @model containment="true"
   * @generated
   */
  VariableValuePairs getVariableValuePairs();

  /**
   * Sets the value of the '{@link org.idm.cms.emodl.emodl.StateEvent#getVariableValuePairs <em>Variable Value Pairs</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable Value Pairs</em>' containment reference.
   * @see #getVariableValuePairs()
   * @generated
   */
  void setVariableValuePairs(VariableValuePairs value);

} // StateEvent
