/**
 * generated by Xtext 2.37.0
 */
package org.idm.cms.emodl.emodl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Time Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.idm.cms.emodl.emodl.TimeEvent#getTime <em>Time</em>}</li>
 *   <li>{@link org.idm.cms.emodl.emodl.TimeEvent#getIterations <em>Iterations</em>}</li>
 *   <li>{@link org.idm.cms.emodl.emodl.TimeEvent#getVariableValuePairs <em>Variable Value Pairs</em>}</li>
 * </ul>
 *
 * @see org.idm.cms.emodl.emodl.EmodlPackage#getTimeEvent()
 * @model
 * @generated
 */
public interface TimeEvent extends Element
{
  /**
   * Returns the value of the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time</em>' attribute.
   * @see #setTime(double)
   * @see org.idm.cms.emodl.emodl.EmodlPackage#getTimeEvent_Time()
   * @model
   * @generated
   */
  double getTime();

  /**
   * Sets the value of the '{@link org.idm.cms.emodl.emodl.TimeEvent#getTime <em>Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time</em>' attribute.
   * @see #getTime()
   * @generated
   */
  void setTime(double value);

  /**
   * Returns the value of the '<em><b>Iterations</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Iterations</em>' attribute.
   * @see #setIterations(int)
   * @see org.idm.cms.emodl.emodl.EmodlPackage#getTimeEvent_Iterations()
   * @model
   * @generated
   */
  int getIterations();

  /**
   * Sets the value of the '{@link org.idm.cms.emodl.emodl.TimeEvent#getIterations <em>Iterations</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Iterations</em>' attribute.
   * @see #getIterations()
   * @generated
   */
  void setIterations(int value);

  /**
   * Returns the value of the '<em><b>Variable Value Pairs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable Value Pairs</em>' containment reference.
   * @see #setVariableValuePairs(VariableValuePairs)
   * @see org.idm.cms.emodl.emodl.EmodlPackage#getTimeEvent_VariableValuePairs()
   * @model containment="true"
   * @generated
   */
  VariableValuePairs getVariableValuePairs();

  /**
   * Sets the value of the '{@link org.idm.cms.emodl.emodl.TimeEvent#getVariableValuePairs <em>Variable Value Pairs</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable Value Pairs</em>' containment reference.
   * @see #getVariableValuePairs()
   * @generated
   */
  void setVariableValuePairs(VariableValuePairs value);

} // TimeEvent
