/**
 * generated by Xtext 2.37.0
 */
package org.idm.cms.emodl.emodl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable Value Pairs</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.idm.cms.emodl.emodl.VariableValuePairs#getVariableValuePairs <em>Variable Value Pairs</em>}</li>
 * </ul>
 *
 * @see org.idm.cms.emodl.emodl.EmodlPackage#getVariableValuePairs()
 * @model
 * @generated
 */
public interface VariableValuePairs extends EObject
{
  /**
   * Returns the value of the '<em><b>Variable Value Pairs</b></em>' containment reference list.
   * The list contents are of type {@link org.idm.cms.emodl.emodl.VariableValuePair}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable Value Pairs</em>' containment reference list.
   * @see org.idm.cms.emodl.emodl.EmodlPackage#getVariableValuePairs_VariableValuePairs()
   * @model containment="true"
   * @generated
   */
  EList<VariableValuePair> getVariableValuePairs();

} // VariableValuePairs
