/*
 * generated by Xtext 2.37.0
 */
package org.idm.cms.emodl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.idm.cms.emodl.ui.internal.EmodlActivator;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EmodlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(EmodlActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		EmodlActivator activator = EmodlActivator.getInstance();
		return activator != null ? activator.getInjector(EmodlActivator.ORG_IDM_CMS_EMODL_EMODL) : null;
	}

}
