/*
 * generated by Xtext 2.37.0
 */
package org.w3.ns.prov.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.w3.ns.prov.ui.internal.ProvActivator;

public class ProvNUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ProvActivator.getInstance().getInjector("org.w3.ns.prov.ProvN");
	}

}
