/**
 * generated by Xtext 2.37.0
 */
package org.idm.cms.emodl.emodl.impl;

import org.eclipse.emf.ecore.EClass;

import org.idm.cms.emodl.emodl.EmodlPackage;
import org.idm.cms.emodl.emodl.Locale;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Locale</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class LocaleImpl extends ElementImpl implements Locale
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LocaleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EmodlPackage.Literals.LOCALE;
  }

} //LocaleImpl
