/**
 * generated by Xtext 2.37.0
 */
package org.idm.cms.emodl.emodl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.idm.cms.emodl.emodl.EmodlPackage;
import org.idm.cms.emodl.emodl.Expression;
import org.idm.cms.emodl.emodl.StateEvent;
import org.idm.cms.emodl.emodl.VariableValuePairs;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>State Event</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.idm.cms.emodl.emodl.impl.StateEventImpl#getPredicate <em>Predicate</em>}</li>
 *   <li>{@link org.idm.cms.emodl.emodl.impl.StateEventImpl#getVariableValuePairs <em>Variable Value Pairs</em>}</li>
 * </ul>
 *
 * @generated
 */
public class StateEventImpl extends ElementImpl implements StateEvent
{
  /**
   * The cached value of the '{@link #getPredicate() <em>Predicate</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPredicate()
   * @generated
   * @ordered
   */
  protected Expression predicate;

  /**
   * The cached value of the '{@link #getVariableValuePairs() <em>Variable Value Pairs</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVariableValuePairs()
   * @generated
   * @ordered
   */
  protected VariableValuePairs variableValuePairs;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StateEventImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EmodlPackage.Literals.STATE_EVENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression getPredicate()
  {
    return predicate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPredicate(Expression newPredicate, NotificationChain msgs)
  {
    Expression oldPredicate = predicate;
    predicate = newPredicate;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, EmodlPackage.STATE_EVENT__PREDICATE, oldPredicate, newPredicate);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPredicate(Expression newPredicate)
  {
    if (newPredicate != predicate)
    {
      NotificationChain msgs = null;
      if (predicate != null)
        msgs = ((InternalEObject)predicate).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - EmodlPackage.STATE_EVENT__PREDICATE, null, msgs);
      if (newPredicate != null)
        msgs = ((InternalEObject)newPredicate).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - EmodlPackage.STATE_EVENT__PREDICATE, null, msgs);
      msgs = basicSetPredicate(newPredicate, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EmodlPackage.STATE_EVENT__PREDICATE, newPredicate, newPredicate));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VariableValuePairs getVariableValuePairs()
  {
    return variableValuePairs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetVariableValuePairs(VariableValuePairs newVariableValuePairs, NotificationChain msgs)
  {
    VariableValuePairs oldVariableValuePairs = variableValuePairs;
    variableValuePairs = newVariableValuePairs;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, EmodlPackage.STATE_EVENT__VARIABLE_VALUE_PAIRS, oldVariableValuePairs, newVariableValuePairs);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVariableValuePairs(VariableValuePairs newVariableValuePairs)
  {
    if (newVariableValuePairs != variableValuePairs)
    {
      NotificationChain msgs = null;
      if (variableValuePairs != null)
        msgs = ((InternalEObject)variableValuePairs).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - EmodlPackage.STATE_EVENT__VARIABLE_VALUE_PAIRS, null, msgs);
      if (newVariableValuePairs != null)
        msgs = ((InternalEObject)newVariableValuePairs).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - EmodlPackage.STATE_EVENT__VARIABLE_VALUE_PAIRS, null, msgs);
      msgs = basicSetVariableValuePairs(newVariableValuePairs, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EmodlPackage.STATE_EVENT__VARIABLE_VALUE_PAIRS, newVariableValuePairs, newVariableValuePairs));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case EmodlPackage.STATE_EVENT__PREDICATE:
        return basicSetPredicate(null, msgs);
      case EmodlPackage.STATE_EVENT__VARIABLE_VALUE_PAIRS:
        return basicSetVariableValuePairs(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EmodlPackage.STATE_EVENT__PREDICATE:
        return getPredicate();
      case EmodlPackage.STATE_EVENT__VARIABLE_VALUE_PAIRS:
        return getVariableValuePairs();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EmodlPackage.STATE_EVENT__PREDICATE:
        setPredicate((Expression)newValue);
        return;
      case EmodlPackage.STATE_EVENT__VARIABLE_VALUE_PAIRS:
        setVariableValuePairs((VariableValuePairs)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EmodlPackage.STATE_EVENT__PREDICATE:
        setPredicate((Expression)null);
        return;
      case EmodlPackage.STATE_EVENT__VARIABLE_VALUE_PAIRS:
        setVariableValuePairs((VariableValuePairs)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EmodlPackage.STATE_EVENT__PREDICATE:
        return predicate != null;
      case EmodlPackage.STATE_EVENT__VARIABLE_VALUE_PAIRS:
        return variableValuePairs != null;
    }
    return super.eIsSet(featureID);
  }

} //StateEventImpl
