/**
 * generated by Xtext 2.37.0
 */
package org.w3.ns.prov.provN;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Document</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.w3.ns.prov.provN.Document#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see org.w3.ns.prov.provN.ProvNPackage#getDocument()
 * @model
 * @generated
 */
public interface Document extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' containment reference.
   * @see #setName(Model)
   * @see org.w3.ns.prov.provN.ProvNPackage#getDocument_Name()
   * @model containment="true"
   * @generated
   */
  Model getName();

  /**
   * Sets the value of the '{@link org.w3.ns.prov.provN.Document#getName <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' containment reference.
   * @see #getName()
   * @generated
   */
  void setName(Model value);

} // Document
