/**
 * generated by Xtext 2.37.0
 */
package org.w3.ns.prov.provN;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Had Member</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.w3.ns.prov.provN.HadMember#getCollection <em>Collection</em>}</li>
 *   <li>{@link org.w3.ns.prov.provN.HadMember#getMember <em>Member</em>}</li>
 * </ul>
 *
 * @see org.w3.ns.prov.provN.ProvNPackage#getHadMember()
 * @model
 * @generated
 */
public interface HadMember extends Relation
{
  /**
   * Returns the value of the '<em><b>Collection</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Collection</em>' reference.
   * @see #setCollection(Entity)
   * @see org.w3.ns.prov.provN.ProvNPackage#getHadMember_Collection()
   * @model
   * @generated
   */
  Entity getCollection();

  /**
   * Sets the value of the '{@link org.w3.ns.prov.provN.HadMember#getCollection <em>Collection</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Collection</em>' reference.
   * @see #getCollection()
   * @generated
   */
  void setCollection(Entity value);

  /**
   * Returns the value of the '<em><b>Member</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Member</em>' reference.
   * @see #setMember(Entity)
   * @see org.w3.ns.prov.provN.ProvNPackage#getHadMember_Member()
   * @model
   * @generated
   */
  Entity getMember();

  /**
   * Sets the value of the '{@link org.w3.ns.prov.provN.HadMember#getMember <em>Member</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Member</em>' reference.
   * @see #getMember()
   * @generated
   */
  void setMember(Entity value);

} // HadMember
