/**
 * generated by Xtext 2.37.0
 */
package org.w3.ns.prov.provN;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.w3.ns.prov.provN.ProvNPackage#getStatement()
 * @model
 * @generated
 */
public interface Statement extends EObject
{
} // Statement
