/**
 * generated by Xtext 2.37.0
 */
package org.w3.ns.prov.provN;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Was Associated With</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.w3.ns.prov.provN.WasAssociatedWith#getActivity <em>Activity</em>}</li>
 *   <li>{@link org.w3.ns.prov.provN.WasAssociatedWith#getAgent <em>Agent</em>}</li>
 *   <li>{@link org.w3.ns.prov.provN.WasAssociatedWith#getPlan <em>Plan</em>}</li>
 *   <li>{@link org.w3.ns.prov.provN.WasAssociatedWith#getAttributes <em>Attributes</em>}</li>
 * </ul>
 *
 * @see org.w3.ns.prov.provN.ProvNPackage#getWasAssociatedWith()
 * @model
 * @generated
 */
public interface WasAssociatedWith extends Relation
{
  /**
   * Returns the value of the '<em><b>Activity</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Activity</em>' reference.
   * @see #setActivity(Activity)
   * @see org.w3.ns.prov.provN.ProvNPackage#getWasAssociatedWith_Activity()
   * @model
   * @generated
   */
  Activity getActivity();

  /**
   * Sets the value of the '{@link org.w3.ns.prov.provN.WasAssociatedWith#getActivity <em>Activity</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Activity</em>' reference.
   * @see #getActivity()
   * @generated
   */
  void setActivity(Activity value);

  /**
   * Returns the value of the '<em><b>Agent</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Agent</em>' reference.
   * @see #setAgent(Agent)
   * @see org.w3.ns.prov.provN.ProvNPackage#getWasAssociatedWith_Agent()
   * @model
   * @generated
   */
  Agent getAgent();

  /**
   * Sets the value of the '{@link org.w3.ns.prov.provN.WasAssociatedWith#getAgent <em>Agent</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Agent</em>' reference.
   * @see #getAgent()
   * @generated
   */
  void setAgent(Agent value);

  /**
   * Returns the value of the '<em><b>Plan</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Plan</em>' reference.
   * @see #setPlan(Entity)
   * @see org.w3.ns.prov.provN.ProvNPackage#getWasAssociatedWith_Plan()
   * @model
   * @generated
   */
  Entity getPlan();

  /**
   * Sets the value of the '{@link org.w3.ns.prov.provN.WasAssociatedWith#getPlan <em>Plan</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Plan</em>' reference.
   * @see #getPlan()
   * @generated
   */
  void setPlan(Entity value);

  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
   * The list contents are of type {@link org.w3.ns.prov.provN.Attribute}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference list.
   * @see org.w3.ns.prov.provN.ProvNPackage#getWasAssociatedWith_Attributes()
   * @model containment="true"
   * @generated
   */
  EList<Attribute> getAttributes();

} // WasAssociatedWith
