/**
 * generated by Xtext 2.37.0
 */
package org.w3.ns.prov.provN;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Was Derived From</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.w3.ns.prov.provN.WasDerivedFrom#getGeneratedEntity <em>Generated Entity</em>}</li>
 *   <li>{@link org.w3.ns.prov.provN.WasDerivedFrom#getUsedEntity <em>Used Entity</em>}</li>
 *   <li>{@link org.w3.ns.prov.provN.WasDerivedFrom#getTime <em>Time</em>}</li>
 *   <li>{@link org.w3.ns.prov.provN.WasDerivedFrom#getAttributes <em>Attributes</em>}</li>
 * </ul>
 *
 * @see org.w3.ns.prov.provN.ProvNPackage#getWasDerivedFrom()
 * @model
 * @generated
 */
public interface WasDerivedFrom extends Relation
{
  /**
   * Returns the value of the '<em><b>Generated Entity</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Generated Entity</em>' reference.
   * @see #setGeneratedEntity(Entity)
   * @see org.w3.ns.prov.provN.ProvNPackage#getWasDerivedFrom_GeneratedEntity()
   * @model
   * @generated
   */
  Entity getGeneratedEntity();

  /**
   * Sets the value of the '{@link org.w3.ns.prov.provN.WasDerivedFrom#getGeneratedEntity <em>Generated Entity</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Generated Entity</em>' reference.
   * @see #getGeneratedEntity()
   * @generated
   */
  void setGeneratedEntity(Entity value);

  /**
   * Returns the value of the '<em><b>Used Entity</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Used Entity</em>' reference.
   * @see #setUsedEntity(Entity)
   * @see org.w3.ns.prov.provN.ProvNPackage#getWasDerivedFrom_UsedEntity()
   * @model
   * @generated
   */
  Entity getUsedEntity();

  /**
   * Sets the value of the '{@link org.w3.ns.prov.provN.WasDerivedFrom#getUsedEntity <em>Used Entity</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Used Entity</em>' reference.
   * @see #getUsedEntity()
   * @generated
   */
  void setUsedEntity(Entity value);

  /**
   * Returns the value of the '<em><b>Time</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time</em>' reference.
   * @see #setTime(DateTime)
   * @see org.w3.ns.prov.provN.ProvNPackage#getWasDerivedFrom_Time()
   * @model
   * @generated
   */
  DateTime getTime();

  /**
   * Sets the value of the '{@link org.w3.ns.prov.provN.WasDerivedFrom#getTime <em>Time</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time</em>' reference.
   * @see #getTime()
   * @generated
   */
  void setTime(DateTime value);

  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
   * The list contents are of type {@link org.w3.ns.prov.provN.Attribute}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference list.
   * @see org.w3.ns.prov.provN.ProvNPackage#getWasDerivedFrom_Attributes()
   * @model containment="true"
   * @generated
   */
  EList<Attribute> getAttributes();

} // WasDerivedFrom
