/**
 * generated by Xtext 2.37.0
 */
package org.w3.ns.prov.provN;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Was Generated By</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.w3.ns.prov.provN.WasGeneratedBy#getEntity <em>Entity</em>}</li>
 *   <li>{@link org.w3.ns.prov.provN.WasGeneratedBy#getActivity <em>Activity</em>}</li>
 *   <li>{@link org.w3.ns.prov.provN.WasGeneratedBy#getTime <em>Time</em>}</li>
 *   <li>{@link org.w3.ns.prov.provN.WasGeneratedBy#getAttributes <em>Attributes</em>}</li>
 * </ul>
 *
 * @see org.w3.ns.prov.provN.ProvNPackage#getWasGeneratedBy()
 * @model
 * @generated
 */
public interface WasGeneratedBy extends Relation
{
  /**
   * Returns the value of the '<em><b>Entity</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity</em>' reference.
   * @see #setEntity(Entity)
   * @see org.w3.ns.prov.provN.ProvNPackage#getWasGeneratedBy_Entity()
   * @model
   * @generated
   */
  Entity getEntity();

  /**
   * Sets the value of the '{@link org.w3.ns.prov.provN.WasGeneratedBy#getEntity <em>Entity</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity</em>' reference.
   * @see #getEntity()
   * @generated
   */
  void setEntity(Entity value);

  /**
   * Returns the value of the '<em><b>Activity</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Activity</em>' reference.
   * @see #setActivity(Activity)
   * @see org.w3.ns.prov.provN.ProvNPackage#getWasGeneratedBy_Activity()
   * @model
   * @generated
   */
  Activity getActivity();

  /**
   * Sets the value of the '{@link org.w3.ns.prov.provN.WasGeneratedBy#getActivity <em>Activity</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Activity</em>' reference.
   * @see #getActivity()
   * @generated
   */
  void setActivity(Activity value);

  /**
   * Returns the value of the '<em><b>Time</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time</em>' containment reference.
   * @see #setTime(DateTime)
   * @see org.w3.ns.prov.provN.ProvNPackage#getWasGeneratedBy_Time()
   * @model containment="true"
   * @generated
   */
  DateTime getTime();

  /**
   * Sets the value of the '{@link org.w3.ns.prov.provN.WasGeneratedBy#getTime <em>Time</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time</em>' containment reference.
   * @see #getTime()
   * @generated
   */
  void setTime(DateTime value);

  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
   * The list contents are of type {@link org.w3.ns.prov.provN.Attribute}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference list.
   * @see org.w3.ns.prov.provN.ProvNPackage#getWasGeneratedBy_Attributes()
   * @model containment="true"
   * @generated
   */
  EList<Attribute> getAttributes();

} // WasGeneratedBy
