/*
 * generated by Xtext 2.37.0
 */
package org.xtext.geodes.trustdsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.geodes.trustdsl.ui.internal.TrustdslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TrustDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(TrustdslActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		TrustdslActivator activator = TrustdslActivator.getInstance();
		return activator != null ? activator.getInjector(TrustdslActivator.ORG_XTEXT_GEODES_TRUSTDSL_TRUSTDSL) : null;
	}

}
