/*
 * generated by Xtext 2.37.0
 */
package org.idm.cms.emodl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.idm.cms.emodl.ui.internal.EmodlActivator;

public class EmodlUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return EmodlActivator.getInstance().getInjector("org.idm.cms.emodl.Emodl");
	}

}
