/*
 * generated by Xtext 2.37.0
 */
package org.w3.ns.prov;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ProvNStandaloneSetup extends ProvNStandaloneSetupGenerated {

	public static void doSetup() {
		new ProvNStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
