/*
 * generated by Xtext 2.37.0
 */
package org.idm.cms.emodl.formatting2;

import org.eclipse.xtext.formatting2.AbstractJavaFormatter;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.formatting2.IHiddenRegionFormatter;
import org.idm.cms.emodl.emodl.EModel;
import org.idm.cms.emodl.emodl.Element;
import org.idm.cms.emodl.emodl.Import;
import org.idm.cms.emodl.emodl.ImportGroup;

public class EmodlFormatter extends AbstractJavaFormatter {

	protected void format(EModel eModel, IFormattableDocument doc) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (Import _import : eModel.getImports()) {
			doc.append(_import, IHiddenRegionFormatter::newLine);
		}
		doc.append(eModel.getStartModel(), IHiddenRegionFormatter::newLine);
		for (Element element : eModel.getElements()) {
			doc.format(element);
			doc.append(element, IHiddenRegionFormatter::newLine);
		}
		doc.append(eModel.getEndModel(), IHiddenRegionFormatter::newLine);
	}

	protected void format(Import _import, IFormattableDocument doc) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (ImportGroup importGroup : _import.getGroups()) {
			
	        doc.append(importGroup, IHiddenRegionFormatter::newLine);
		}
	}
	
	// TODO: implement for Function, Observable, Reaction, StateEvent, TimeEvent, VariableValuePairs, VariableValuePair, Expression
}
