/*
 * generated by Xtext 2.37.0
 */
package org.w3.ns.prov.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractProvNScopeProvider extends DelegatingScopeProvider {
}
