/*
 * generated by Xtext 2.37.0
 */
package org.xtext.geodes.trustdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TrustDSLUiModule extends AbstractTrustDSLUiModule {

	public TrustDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
