/*
 * generated by Xtext 2.37.0
 */
package org.idm.cms.emodl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractEmodlValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.idm.cms.emodl.emodl.EmodlPackage.eINSTANCE);
		return result;
	}
}
