/*
 * generated by Xtext 2.37.0
 */
package org.xtext.geodes.trustdsl.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class TrustDSLProposalProvider extends AbstractTrustDSLProposalProvider {
}
