/*
 * generated by Xtext 2.37.0
 */
package org.xtext.geodes.trustdsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.geodes.trustdsl.ui.internal.TrustdslActivator;

public class TrustDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TrustdslActivator.getInstance().getInjector("org.xtext.geodes.trustdsl.TrustDSL");
	}

}
