/*
 * generated by Xtext 2.37.0
 */
package org.idm.cms.emodl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.idm.cms.emodl.EmodlRuntimeModule;
import org.idm.cms.emodl.EmodlStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class EmodlIdeSetup extends EmodlStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new EmodlRuntimeModule(), new EmodlIdeModule()));
	}
	
}
