/*
 * generated by Xtext 2.37.0
 */
package org.xtext.geodes.trustdsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.geodes.trustdsl.TrustDSLRuntimeModule;
import org.xtext.geodes.trustdsl.TrustDSLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class TrustDSLIdeSetup extends TrustDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TrustDSLRuntimeModule(), new TrustDSLIdeModule()));
	}
	
}
