/*
 * generated by Xtext 2.37.0
 */
package org.w3.ns.prov.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.w3.ns.prov.ui.internal.ProvActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ProvNExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(ProvActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		ProvActivator activator = ProvActivator.getInstance();
		return activator != null ? activator.getInjector(ProvActivator.ORG_W3_NS_PROV_PROVN) : null;
	}

}
