/*
 * generated by Xtext 2.37.0
 */
package org.idm.cms.emodl.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class EmodlProposalProvider extends AbstractEmodlProposalProvider {
}
