/*
 * generated by Xtext 2.37.0
 */
package org.idm.cms.emodl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class EmodlStandaloneSetup extends EmodlStandaloneSetupGenerated {

	public static void doSetup() {
		new EmodlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
