/**
 * generated by Xtext 2.37.0
 */
package org.xtext.geodes.trustdsl.trustDSL.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.geodes.trustdsl.trustDSL.Agent;
import org.xtext.geodes.trustdsl.trustDSL.TrustDSLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Agent</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AgentImpl extends ElementImpl implements Agent
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AgentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TrustDSLPackage.Literals.AGENT;
  }

} //AgentImpl
