/*
 * generated by Xtext 2.37.0
 */
package org.w3.ns.prov.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.w3.ns.prov.parser.antlr.internal.InternalProvNParser;
import org.w3.ns.prov.services.ProvNGrammarAccess;

public class ProvNParser extends AbstractAntlrParser {

	@Inject
	private ProvNGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalProvNParser createParser(XtextTokenStream stream) {
		return new InternalProvNParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Document";
	}

	public ProvNGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ProvNGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
