/*
 * generated by Xtext 2.37.0
 */
package org.xtext.geodes.trustdsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TrustDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/geodes/trustdsl/parser/antlr/internal/InternalTrustDSL.tokens");
	}
}
